import type { Metadata } from "next";
import { GeistSans } from "geist/font";
import "./globals.css";
import { Providers } from "./providers";
import SideBar from "@/components/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Providers>
          <div className="flex p-10 min-h-screen justify-center">
            <SideBar />
            <div className="px-10">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
